#!/usr/bin/env bash

set -e

# Install gcc5 if we're on Linux.  For OSX, we'll depend on the XCode-provided
# default compiler
if [ "$(uname)" -eq "Linux" ] ; then
    add-apt-repository -y ppa:ubuntu-toolchain-r/test
    apt-get update -y
    apt-get install -y build-essential
    apt-get install -y gcc-5 g++-5
    apt-get install -y lvm2 libexpat-dev openssl libssl-dev libbz2-dev
    apt-get install -y pkg-config
fi

# Setup /data
$app_dir/deploy/configure-volumes

# move /tmp to /data
mkdir -p /data/tmp
chmod a+rwx /data/tmp
mv /tmp/* /data/tmp
rmdir /tmp
ln -s /data/tmp /tmp

# Download OSM map data
pushd /data
aws s3 cp "$S3URL" .
aws s3 cp "${S3URL}.md5" .
filename="${S3URL##*/}"
extension="${filename##*.}"
md5sum -c "${filename}.md5"
echo "${filename}" > latest
popd

# Build route-annotatord
export CXX=g++-5
export CC=gcc-5
./bootstrap.sh
mkdir -p bin
mv build/Release/route-annotatord bin


# Start it up
source /etc/profile
cat $app_dir/deploy/route-annotator.conf | $bp_dir/common/replacer.sh > /etc/init/route-annotator.conf
start route-annotator
